diffusion_train:
  device: "cuda"
  EPOCHS: 100
  LR : 0.001
  NUM_WORKERS: 255
  BATCH_SIZE : 128
  VIS_EPOCHS : 25
  MODEL_DIR : "src/optimization_loop/train_diffusion/weigths/Unet_weights"
  LOG_DIR : "src/optimization_loop/train_diffusion/weigths/Unet_logs"
  dpp_epoch_tres : -100
  cash_dpp_loss : 0
  LAMBDA_DPP : 0.01
  LAMBDA_QUALITY : 0.5
  if_dpp: True
  DPP_WEIGTHS : [0.5,0.5]
  Unet_starting_path : "src/diffusion_notebooks/DIffusion_model_weigths_and_datas/model_epoch_499_RMSnorm_unscaled.pt"
  
data:
  # for  diffusion training
  # the name of the files inside the Base_DATA_DIR is needed  only 
  BASE_DATA_DIR: "data_MPI"
  xs_train_path: "xs_train_MPI.npy"
  ys_train_path:  "ys_train_MPI.npy"
  coord_min_max_path: "coord_min_max.npy"
  label_min_max_path: "label_min_max.npy"
  # for surrogate_model training



UA_surrogate_model:

  device : "cuda"
  init_path: "src/surrogate_models/mlp_best_model_final.pt"
  # init_cl_path: "src/optimization_loop/Inner_loop/UA_surrogate_weights/cl/mlp_best_model_cl_150_200_200_150.pt"
  # init_cd_path: "src/optimization_loop/Inner_loop/UA_surrogate_weights/cd/mlp_best_model_cd_200_300_300_200.pt"
  all_weigths_path: None


surrogate_train:
  train_flag: False
  # train_flag: True
  device: "cuda"
  input_size: 384
  NUM_WORKERS: 255
  BATCH_SIZE: 128
  EPOCHS: 100
  LR : 0.0001
  hidden_layers: [150,200,200,150]
  patience: 40
  MODEL_DIR : "src/optimization_loop/train_diffusion/weigths/surrogate_weigths"
  LOG_DIR : "src/optimization_loop/train_diffusion/weigths/surrogate_logs"
  LAMBDA_CD: 100
  LAMBDA_CL: 1
  
